import {
  BadRequestException,
  ConflictException,
  ForbiddenException,
  Inject,
  Injectable,
  Logger,
  NotFoundException,
  forwardRef,
} from '@nestjs/common';
import { SubmissionStatus, UserRole, type Prisma } from '@prisma/client';
import { randomUUID } from 'node:crypto';
import { PrismaService } from '../prisma/prisma.service.js';
import { StorageService } from '../storage/storage.service.js';
import { PhotoPipelineWorker } from '../photo/photo-pipeline.worker.js';
import { SubmissionDedupService } from '../photo/submission-dedup.service.js';
import { PriceService, type StationPriceRow } from '../price/price.service.js';
import { PriceCacheService } from '../price/price-cache.service.js';
import { VALID_FUEL_TYPES } from '../price/config/price-modifiers.js';

type PriceEntry = { fuel_type: string; price_per_litre: number | null };

type MappedSubmission = {
  id: string;
  station: { id: string; name: string } | null;
  price_data: PriceEntry[];
  status: 'pending' | 'verified' | 'rejected' | 'shadow_rejected';
  flag_reason: string | null;
  created_at: Date;
};

export interface CreateSubmissionFields {
  fuelType: string;
  gpsLat: number | null;
  gpsLng: number | null;
  manualPrice: number | null;
  preselectedStationId: string | null;
  // Story 3.20 — capture-screen telemetry. All optional; pre-3.20 clients
  // omit them (the row stays null on those fields).
  gpsAcquiredAtCapture?: boolean | null;
  gpsAcquisitionMs?: number | null;
  overrideUsed?: boolean | null;
  nearbyStationsCount?: number | null;
}

const FLAG_WRONG_WINDOW_MS = 24 * 3600 * 1000;
const AUDIT_ACTION_USER_FLAGGED = 'USER_FLAGGED_WRONG';
const AUDIT_ACTION_AUTO_RESOLVED = 'AUTO_RESOLVED_BY_RESUBMIT';
// Story 3.16 — emitted by detectAndRoutePriceConflict for traceability
// of every conflict pair generated by the consensus dedup path.
const AUDIT_ACTION_PRICE_CONFLICT = 'PRICE_CONFLICT_DETECTED';

// P-2: previous-verified submission must be within this window to be eligible
// for restore. Older than this and we'd be repopulating the cache with prices
// that may have shifted significantly — better to fall through to estimates.
const RESTORE_PREVIOUS_MAX_AGE_MS = 7 * 24 * 3600 * 1000;

// BS-1: explicit allowlist of flag_reason values that are visible to drivers
// in their activity log. Anything not in this set is laundered to null on the
// wire to avoid leaking internal taxonomy (rule ids, anti-fraud signals, etc.).
// Keep in sync with the AC5 reason-aware copy in mobile SubmissionRow.tsx.
const DRIVER_VISIBLE_FLAG_REASONS: ReadonlySet<string> = new Set([
  'user_flagged_wrong',
  'price_conflict',
  'pb95_outside_rack_band',
  'on_outside_rack_band',
  'lpg_outside_rack_band',
]);

const VALID_FUEL_TYPES_SET: ReadonlySet<string> = new Set(VALID_FUEL_TYPES);

@Injectable()
export class SubmissionsService {
  private readonly logger = new Logger(SubmissionsService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly storageService: StorageService,
    @Inject(forwardRef(() => PhotoPipelineWorker))
    private readonly photoPipelineWorker: PhotoPipelineWorker,
    private readonly submissionDedupService: SubmissionDedupService,
    private readonly priceService: PriceService,
    private readonly priceCache: PriceCacheService,
  ) {}

  /**
   * Activity-screen summary (verified-only aggregates).
   *
   * The activity screen previously derived these counts from whatever
   * page of submissions was loaded, which made the header values grow
   * as the driver paginated. This returns account-wide totals so the
   * card reflects "13 submissions / 13 stations / Active since Jan 4"
   * regardless of pagination state.
   *
   * Verified-only by design — pending/rejected/shadow_rejected rows
   * shouldn't inflate the contribution count the driver sees.
   */
  async getMySubmissionsSummary(userId: string): Promise<{
    verifiedCount: number;
    stationsCovered: number;
    activeSince: Date | null;
  }> {
    const [count, distinctStations, earliest] = await Promise.all([
      this.prisma.submission.count({
        where: { user_id: userId, status: SubmissionStatus.verified },
      }),
      this.prisma.submission.findMany({
        where: {
          user_id: userId,
          status: SubmissionStatus.verified,
          station_id: { not: null },
        },
        distinct: ['station_id'],
        select: { station_id: true },
      }),
      this.prisma.submission.findFirst({
        where: { user_id: userId, status: SubmissionStatus.verified },
        orderBy: { created_at: 'asc' },
        select: { created_at: true },
      }),
    ]);

    return {
      verifiedCount: count,
      stationsCovered: distinctStations.length,
      activeSince: earliest?.created_at ?? null,
    };
  }

  async getMySubmissions(userId: string, page: number, limit: number) {
    const skip = (page - 1) * limit;

    const [items, total] = await Promise.all([
      this.prisma.submission.findMany({
        where: { user_id: userId },
        include: { station: { select: { id: true, name: true } } },
        orderBy: { created_at: 'desc' },
        skip,
        take: limit,
      }),
      this.prisma.submission.count({ where: { user_id: userId } }),
    ]);

    const data: MappedSubmission[] = items.map((item) => {
      // Story 4.3: shadow_banned drivers must not learn they're banned, so
      // shadow_rejected with flag_reason='shadow_banned' is laundered to
      // 'pending' on the wire. All OTHER shadow_rejected reasons are passed
      // through (Story 3.14 — drivers need to see their flagged submissions
      // and rule-based shadow_rejects so they understand why prices aren't
      // showing).
      let status: MappedSubmission['status'];
      if (item.status === SubmissionStatus.shadow_rejected && item.flag_reason === 'shadow_banned') {
        status = 'pending';
      } else if (
        item.status === SubmissionStatus.pending ||
        item.status === SubmissionStatus.verified ||
        item.status === SubmissionStatus.rejected ||
        item.status === SubmissionStatus.shadow_rejected
      ) {
        status = item.status;
      } else {
        status = 'pending';
      }

      // BS-1: explicit allowlist of driver-visible flag_reason values. Any
      // value not in DRIVER_VISIBLE_FLAG_REASONS (including the laundered
      // 'shadow_banned' case) is set to null on the wire so future internal
      // taxonomy doesn't leak.
      const flag_reason =
        item.flag_reason && DRIVER_VISIBLE_FLAG_REASONS.has(item.flag_reason)
          ? item.flag_reason
          : null;

      return {
        id: item.id,
        station: item.station,
        price_data: Array.isArray(item.price_data) ? (item.price_data as PriceEntry[]) : [],
        status,
        flag_reason,
        created_at: item.created_at,
      };
    });

    return { data, total, page, limit };
  }

  /**
   * AC1: Upload photo to R2 first — if this fails, no Submission record is created (AC3).
   * AC2: Create Submission with status=pending, then enqueue BullMQ job (AC4).
   * Returns void; caller returns 202 Accepted.
   */
  async createSubmission(
    userId: string,
    photoBuffer: Buffer,
    fields: CreateSubmissionFields,
  ): Promise<void> {
    // Story 4.3: Shadow ban short-circuit — silently creates a shadow_rejected record so the user
    // sees a normal 202 response but no data enters the pipeline.
    // Wrapped in a transaction to prevent TOCTOU race between the ban check and the create.
    const shadowBanned = await this.prisma.$transaction(async (tx) => {
      const user = await tx.user.findUnique({
        where: { id: userId },
        select: { shadow_banned: true },
      });
      if (user?.shadow_banned) {
        await tx.submission.create({
          data: {
            user_id: userId,
            station_id: null,
            photo_r2_key: null,
            gps_lat: null,
            gps_lng: null,
            price_data: [],
            status: SubmissionStatus.shadow_rejected,
            flag_reason: 'shadow_banned',
          },
        });
        return true;
      }
      return false;
    });
    if (shadowBanned) return;

    // Story 3.10/3.16: L1 station consensus check — preselected path only
    // (stationId unknown for GPS path). Only skip intake when the station
    // has a CONFIRMED consensus record (count: 2). 'corroborate-candidate'
    // submissions still go through so the worker can confirm or conflict.
    if (fields.preselectedStationId) {
      try {
        const decision = await this.submissionDedupService.checkStationConsensus(
          fields.preselectedStationId,
        );
        if (decision.skip) {
          this.logger.log(
            `[DEDUP-L1] station=${fields.preselectedStationId} — confirmed corroboration exists, skipping intake`,
          );
          return;
        }
      } catch (e: unknown) {
        this.logger.warn(`[DEDUP-L1] Redis check failed, proceeding normally: ${(e as Error).message}`);
      }
    }

    const submissionId = randomUUID();
    const r2Key = `submissions/${userId}/${submissionId}.jpg`;

    // AC3: R2 upload BEFORE DB insert — failure propagates, no orphan Submission record
    await this.storageService.uploadBuffer(r2Key, photoBuffer, 'image/jpeg');

    try {
      await this.prisma.submission.create({
        data: {
          id: submissionId,
          user_id: userId,
          station_id: fields.preselectedStationId ?? null,
          photo_r2_key: r2Key,
          gps_lat: fields.gpsLat,
          gps_lng: fields.gpsLng,
          price_data: [{ fuel_type: fields.fuelType, price_per_litre: fields.manualPrice }],
          status: SubmissionStatus.pending,
          // Story 3.20 — capture-screen telemetry pass-through. Undefined
          // becomes null in Prisma; pre-3.20 clients omit these fields and
          // the row stays null.
          gps_acquired_at_capture: fields.gpsAcquiredAtCapture ?? null,
          gps_acquisition_ms: fields.gpsAcquisitionMs ?? null,
          override_used: fields.overrideUsed ?? null,
          nearby_stations_count: fields.nearbyStationsCount ?? null,
        },
      });
    } catch (dbErr) {
      // DB failed after R2 succeeded — best-effort cleanup to avoid orphan R2 object
      await this.storageService.deleteObject(r2Key).catch(() => {});
      throw dbErr;
    }

    try {
      // AC4: job payload is submissionId only — worker fetches all data from DB
      await this.photoPipelineWorker.enqueue(submissionId);
    } catch (queueErr) {
      // Queue failed after DB create — roll back both DB record and R2 object
      await this.prisma.submission.delete({ where: { id: submissionId } }).catch(() => {});
      await this.storageService.deleteObject(r2Key).catch(() => {});
      throw queueErr;
    }
  }

  /**
   * Story 3.14 — driver-initiated withdrawal of a verified submission.
   *
   * Flow:
   *   1. Auth: caller must own the submission
   *   2. Status: must be `verified` (idempotent: 409 if already moved)
   *   3. Window: created within last 24h (admins bypass)
   *   4. Atomic transition: verified → shadow_rejected, flag_reason='user_flagged_wrong'
   *   5. Restore prices: find previous verified submission for the station and
   *      replay its prices via setVerifiedPrice; if none, invalidate cache so
   *      the read-path falls back through estimates
   *   6. Lift dedup: delete dedup:station:{id} and dedup:hash:{photoHash}
   *      (best-effort, doesn't block on Redis errors)
   *   7. Audit log
   */
  async flagWrong(
    submissionId: string,
    actorUserId: string,
    actorRole: UserRole,
  ): Promise<void> {
    const submission = await this.prisma.submission.findUnique({
      where: { id: submissionId },
      select: {
        id: true,
        user_id: true,
        station_id: true,
        photo_r2_key: true,
        status: true,
        flag_reason: true,
        created_at: true,
      },
    });

    if (!submission) {
      throw new NotFoundException(`Submission ${submissionId} not found`);
    }
    if (submission.user_id !== actorUserId) {
      throw new ForbiddenException(`Submission ${submissionId} does not belong to caller`);
    }
    if (submission.status !== SubmissionStatus.verified) {
      throw new ConflictException(
        `Submission ${submissionId} cannot be flagged from status ${submission.status} — only verified is supported`,
      );
    }

    // Window check — admins bypass per Story 3.14 admin-bypass exception.
    // P-17: also reject negative ageMs (future created_at) so a clock-skewed
    // server timestamp can't trivially pass the <= 24h check.
    if (actorRole !== UserRole.ADMIN) {
      const ageMs = Date.now() - submission.created_at.getTime();
      if (ageMs < 0 || ageMs > FLAG_WRONG_WINDOW_MS) {
        throw new BadRequestException(
          `Submission ${submissionId} is older than 24h or has an invalid timestamp — flag-wrong window has closed`,
        );
      }
    }

    // P-9: lift dedup BEFORE the status flip. liftDedup is idempotent (DEL
    // ignores missing keys), and lifting first means a request cut off
    // mid-method leaves the user able to retry: the row is still `verified`
    // (so the next call passes the status guard) and the dedup keys are
    // already lifted (so the retake can immediately re-process). Without
    // this ordering the user could be permanently locked out of recovery
    // after a single network hiccup.
    let photoHash: string | null = null;
    if (submission.photo_r2_key) {
      try {
        const buf = await this.storageService.getObjectBuffer(submission.photo_r2_key);
        photoHash = SubmissionDedupService.computePhotoHash(buf);
      } catch (e) {
        this.logger.warn(
          `Submission ${submissionId}: could not compute photo hash for dedup lift: ${
            e instanceof Error ? e.message : String(e)
          }`,
        );
      }
    }
    await this.submissionDedupService.liftDedup(submission.station_id, photoHash);

    // Atomic guard: if a concurrent admin or another flag-wrong already moved
    // the row, updateMany returns count=0 and we 409. Dedup is already lifted
    // by this point — acceptable because the lift is idempotent and the
    // station's dedup window will re-establish on the next verified submission.
    const updateResult = await this.prisma.submission.updateMany({
      where: { id: submissionId, status: SubmissionStatus.verified },
      data: {
        status: SubmissionStatus.shadow_rejected,
        flag_reason: 'user_flagged_wrong',
      },
    });
    if (updateResult.count === 0) {
      throw new ConflictException(
        `Submission ${submissionId} was modified concurrently — flag-wrong aborted`,
      );
    }

    // Restore previous verified submission's prices for this station. Done
    // AFTER the status flip so the just-flagged submission is excluded by
    // the live status filter, even if the explicit excludeIds guard is bypassed.
    const restoredFromId = submission.station_id
      ? await this.restorePreviousPrices(submission.station_id, [submissionId])
      : null;

    // Audit trail. Reuses AdminAuditLog (action prefixed USER_ for clarity);
    // admin_user_id field stores the actor's user_id regardless of role —
    // it's a text column with no FK constraint.
    // P-13: preserve previous_flag_reason in notes so a custom annotation
    // (e.g., admin's pre-flag note) isn't silently lost when the flag-wrong
    // overwrites flag_reason.
    await this.prisma.adminAuditLog
      .create({
        data: {
          admin_user_id: actorUserId,
          action: AUDIT_ACTION_USER_FLAGGED,
          submission_id: submissionId,
          notes: JSON.stringify({
            previous_status: 'verified',
            previous_flag_reason: submission.flag_reason,
            restored_from_submission_id: restoredFromId,
            actor_role: actorRole,
          }),
        },
      })
      .catch((err: unknown) => {
        // Log-only — audit failure mustn't block the flag action.
        this.logger.error(
          `Submission ${submissionId}: audit log write failed: ${
            err instanceof Error ? err.message : String(err)
          }`,
        );
      });

    this.logger.log(
      `Submission ${submissionId} flagged by user ${actorUserId} — ` +
        `restored from ${restoredFromId ?? 'none (cache invalidated)'}`,
    );
  }

  /**
   * Story 3.14 AC6 — when a driver successfully verifies a new submission at
   * a station where they had previously flagged-wrong an earlier submission,
   * auto-close that earlier flagged submission so admin doesn't have to
   * review it (the driver's resubmission counts as resolution).
   *
   * Best-effort: any failure here is logged but doesn't block the new
   * submission's verification flow. Called from photo-pipeline.worker right
   * after a successful setVerifiedPrice.
   *
   * P-6: only resolves flags filed BEFORE the triggering submission was
   * captured. A BullMQ retry of an old verify-job must not auto-resolve a
   * flag the driver filed after the original verification completed.
   */
  async autoResolveFlaggedAtStation(
    userId: string,
    stationId: string,
    triggeringSubmissionId: string,
    triggeringCreatedAt: Date,
  ): Promise<void> {
    const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 3600 * 1000);
    const flagged = await this.prisma.submission.findMany({
      where: {
        user_id: userId,
        station_id: stationId,
        status: SubmissionStatus.shadow_rejected,
        flag_reason: 'user_flagged_wrong',
        created_at: { gte: sevenDaysAgo, lt: triggeringCreatedAt },
        id: { not: triggeringSubmissionId },
      },
      select: { id: true },
    });

    if (flagged.length === 0) return;

    const flaggedIds = flagged.map((f) => f.id);
    // P-5: status + flag_reason guard in the WHERE clause. If an admin moved
    // a row out of `shadow_rejected/user_flagged_wrong` between the findMany
    // and this updateMany (e.g., admin manually verified the flag because
    // the prices were actually correct), we MUST NOT silently overwrite that.
    // The `count` returned will be lower than `flaggedIds.length` in that
    // case; we audit only the rows that actually changed.
    const updated = await this.prisma.submission.updateMany({
      where: {
        id: { in: flaggedIds },
        status: SubmissionStatus.shadow_rejected,
        flag_reason: 'user_flagged_wrong',
      },
      data: {
        status: SubmissionStatus.rejected,
        flag_reason: 'auto_resolved_by_resubmit',
      },
    });

    if (updated.count === 0) {
      this.logger.log(
        `Auto-resolve: ${flaggedIds.length} flagged submission(s) at station ${stationId} for user ${userId} were already moved by admin — no action`,
      );
      return;
    }

    // Audit trail for each auto-resolve so admins can trace the chain. We
    // audit the rows we INTENDED to resolve; if some were already moved by
    // admin, the audit row pairs with the post-update state via timestamp.
    // Failures are per-row .catch'd so a single audit hiccup doesn't drop
    // the rest. (Sequential rather than Promise.all to avoid flooding the
    // connection pool when many rows resolve at once.)
    for (const id of flaggedIds) {
      await this.prisma.adminAuditLog
        .create({
          data: {
            admin_user_id: userId,
            action: AUDIT_ACTION_AUTO_RESOLVED,
            submission_id: id,
            notes: JSON.stringify({ resolved_by_submission_id: triggeringSubmissionId }),
          },
        })
        .catch((err: unknown) => {
          this.logger.warn(
            `Auto-resolve audit log failed for submission ${id}: ${
              err instanceof Error ? err.message : String(err)
            }`,
          );
        });
    }

    this.logger.log(
      `Auto-resolved ${updated.count}/${flaggedIds.length} flagged submission(s) at station ${stationId} for user ${userId} — triggered by ${triggeringSubmissionId}`,
    );
  }

  /**
   * Story 3.16 AC7 — second submission's prices disagree with the previous
   * verified submission beyond the ±0.05 PLN/l noise threshold. Pair both
   * via a new `conflict_group_id`, route both to admin shadow_rejected,
   * roll the cache back to the prior verified submission (if any), and
   * clear the dedup record so the next submission starts fresh.
   *
   * Called from the photo pipeline worker after OCR + price validation,
   * BEFORE the worker would have called `setVerifiedPrice`. The new
   * submission was just OCR'd successfully but still has `status: pending` —
   * this method flips it to `shadow_rejected` (no `verified` intermediate
   * state) and persists its validated prices in the same write.
   *
   * P-2 (3.16 review) — Step ordering: the NEW submission is flipped to
   * shadow_rejected FIRST. If anything after that throws, the row is at
   * least findable in the admin queue (orphan-partner case AC10 handles
   * the missing-partner branch). The earlier order (find previous → flip
   * previous → flip new) left the new row in `pending` if find/flip-prev
   * failed; the worker's `.catch()` then swallowed the error and the
   * submission was effectively lost.
   *
   * P-3 (3.16 review) — The new submission's flip persists `price_data`,
   * `gps_lat: null`, `gps_lng: null` in the SAME `update` so a reader
   * never sees a `pending` row with new prices but no conflict status.
   */
  async detectAndRoutePriceConflict(args: {
    stationId: string;
    newSubmissionId: string;
    newSubmissionUserId: string;
    newPriceData: PriceEntry[];
    newPricesHash: string;
    prevPricesHash: string | null;
  }): Promise<{ conflict_group_id: string; partner_submission_id: string | null }> {
    const {
      stationId,
      newSubmissionId,
      newSubmissionUserId,
      newPriceData,
      newPricesHash,
      prevPricesHash,
    } = args;
    const conflict_group_id = randomUUID();

    // 1. Flip the NEW submission FIRST. Status guard ensures we don't
    //    overwrite a row that a concurrent action (admin reject, user
    //    flag-wrong, BullMQ retry that already routed) already moved
    //    out of `pending`. Persists validated prices and nulls GPS in the
    //    same write so admin can see what each side claimed without
    //    ever exposing them on the map.
    const newUpdated = await this.prisma.submission.updateMany({
      where: { id: newSubmissionId, status: SubmissionStatus.pending },
      data: {
        status: SubmissionStatus.shadow_rejected,
        flag_reason: 'price_conflict',
        conflict_group_id,
        price_data: newPriceData as unknown as Prisma.InputJsonValue,
        gps_lat: null,
        gps_lng: null,
      },
    });
    if (newUpdated.count === 0) {
      // Another actor moved the row — back out cleanly. The dedup record
      // and previous-verified state are untouched at this point.
      this.logger.warn(
        `detectAndRoutePriceConflict: new submission ${newSubmissionId} no longer pending (concurrent action) — aborting conflict routing`,
      );
      return { conflict_group_id, partner_submission_id: null };
    }

    // 2. Find the previous-newest verified submission for this station so
    //    we can pair it with the new one. Bound by the 7-day restore
    //    window — older "previous" rows are too stale to claim as the
    //    immediate disagreement partner; we'd just route the new one
    //    alone and let admin handle it as a single-row review.
    const minCreatedAt = new Date(Date.now() - RESTORE_PREVIOUS_MAX_AGE_MS);
    const previous = await this.prisma.submission.findFirst({
      where: {
        station_id: stationId,
        status: SubmissionStatus.verified,
        created_at: { gte: minCreatedAt },
        id: { not: newSubmissionId },
      },
      orderBy: { created_at: 'desc' },
      select: { id: true },
    });

    let partner_submission_id: string | null = null;

    // 3. Atomic flip on the previous verified row, guarded by status.
    //    If a concurrent admin already moved it (count: 0), leave it
    //    alone — the new row already has the conflict_group_id (step 1)
    //    and the admin queue will surface it as a single-row review.
    if (previous) {
      const partnerUpdated = await this.prisma.submission.updateMany({
        where: { id: previous.id, status: SubmissionStatus.verified },
        data: {
          status: SubmissionStatus.shadow_rejected,
          flag_reason: 'price_conflict',
          conflict_group_id,
        },
      });
      if (partnerUpdated.count === 1) {
        partner_submission_id = previous.id;
      } else {
        this.logger.warn(
          `detectAndRoutePriceConflict: previous submission ${previous.id} for station ${stationId} was moved by another actor — proceeding with newer-only conflict record`,
        );
      }
    }

    // 4. Roll the cache back to the prior verified row that ISN'T part of
    //    this new conflict pair. Excludes both the new submission and the
    //    just-flipped previous (if any) so we don't restore from a row we
    //    just shadow_rejected.
    const excludeIds = previous
      ? [newSubmissionId, previous.id]
      : [newSubmissionId];
    const restoredFromId = await this.restorePreviousPrices(stationId, excludeIds);

    // 5. Clear the dedup record entirely — next submission starts at AC1.
    //    Reuses Story 3.14's lift method (station-only; no photo hash to lift).
    await this.submissionDedupService.liftDedup(stationId, null);

    // 6. Audit trail — best-effort. P-1 (3.16 review): use the actor's
    //    user_id rather than the magic string 'system' so audit-by-user
    //    queries surface this action attributable to the driver who
    //    triggered the conflict; the system-vs-user distinction is
    //    captured in the `actor_role` notes field, mirroring 3.14.
    await this.prisma.adminAuditLog
      .create({
        data: {
          admin_user_id: newSubmissionUserId,
          action: AUDIT_ACTION_PRICE_CONFLICT,
          submission_id: newSubmissionId,
          notes: JSON.stringify({
            actor_role: 'system',
            partner_submission_id,
            conflict_group_id,
            restored_from_submission_id: restoredFromId,
            prev_prices_hash: prevPricesHash,
            new_prices_hash: newPricesHash,
          }),
        },
      })
      .catch((err: unknown) => {
        this.logger.error(
          `detectAndRoutePriceConflict: audit log write failed for ${newSubmissionId}: ${
            err instanceof Error ? err.message : String(err)
          }`,
        );
      });

    this.logger.log(
      `Price conflict ${conflict_group_id}: station ${stationId}, new ${newSubmissionId}, partner ${
        partner_submission_id ?? 'none'
      }, restored from ${restoredFromId ?? 'none (cache invalidated)'}`,
    );

    return { conflict_group_id, partner_submission_id };
  }

  /**
   * Find the most recent verified submission for a station (excluding `excludeId`)
   * within the restore window, convert its price_data to a StationPriceRow,
   * and write it via priceService.setVerifiedPrice. If none exists or its
   * data is unusable, invalidate the cache so the read-path falls back
   * through estimates. Returns the source submission id, or null if no
   * restore happened (cache was invalidated instead).
   */
  private async restorePreviousPrices(
    stationId: string,
    excludeIds: string[],
  ): Promise<string | null> {
    // P-2: bound the search to a sensible recency window. Restoring a 6-month-old
    // price as the live community price would mislead drivers more than falling
    // back to estimates.
    const minCreatedAt = new Date(Date.now() - RESTORE_PREVIOUS_MAX_AGE_MS);
    const previous = await this.prisma.submission.findFirst({
      where: {
        station_id: stationId,
        status: SubmissionStatus.verified,
        created_at: { gte: minCreatedAt },
        id: { notIn: excludeIds },
      },
      orderBy: { created_at: 'desc' },
      select: { id: true, price_data: true, created_at: true },
    });

    if (!previous) {
      await this.invalidateOrLog(stationId, 'no recent previous verified submission');
      return null;
    }

    const priceData = Array.isArray(previous.price_data)
      ? (previous.price_data as Array<{ fuel_type: string; price_per_litre: number | null }>)
      : [];
    // P-4: also validate fuel_type against the known set so a malformed
    // legacy price_data row can't poison the cache with unknown fuel keys.
    const validEntries = priceData.filter(
      (p): p is { fuel_type: string; price_per_litre: number } =>
        typeof p.fuel_type === 'string' &&
        VALID_FUEL_TYPES_SET.has(p.fuel_type) &&
        typeof p.price_per_litre === 'number' &&
        Number.isFinite(p.price_per_litre),
    );

    // P-3: an empty validEntries set would write an empty {} cache row,
    // poisoning the cache with "no prices known" instead of letting the
    // read-path fall through to estimates. Branch to invalidate.
    if (validEntries.length === 0) {
      await this.invalidateOrLog(
        stationId,
        `previous submission ${previous.id} had no valid price entries`,
      );
      return null;
    }

    const priceRow: StationPriceRow = {
      stationId,
      prices: Object.fromEntries(validEntries.map((p) => [p.fuel_type, p.price_per_litre])),
      sources: Object.fromEntries(validEntries.map((p) => [p.fuel_type, 'community' as const])),
      // P-1: use the current time so freshness banners and stale filters
      // see the restored row as a live update, not a historical timestamp.
      updatedAt: new Date(),
    };

    try {
      await this.priceService.setVerifiedPrice(stationId, priceRow);
    } catch (e) {
      this.logger.warn(
        `restorePreviousPrices: setVerifiedPrice failed for station ${stationId}: ${
          e instanceof Error ? e.message : String(e)
        }. Falling back to cache invalidate.`,
      );
      await this.priceCache.invalidate(stationId).catch(() => undefined);
    }

    return previous.id;
  }

  /** Best-effort cache invalidation with a contextual log line. */
  private async invalidateOrLog(stationId: string, reason: string): Promise<void> {
    try {
      await this.priceCache.invalidate(stationId);
    } catch (e) {
      this.logger.warn(
        `restorePreviousPrices: cache invalidate failed for station ${stationId} (${reason}): ${
          e instanceof Error ? e.message : String(e)
        }`,
      );
    }
  }
}
